# shellcheck shell=bash
#
# rpm.sh - turn the staged tree into an .rpm using rpmbuild.
#
# Upgrades "just work" because every package keeps the same Name (antigravity /
# antigravity-ide) and only the Version changes. rpm compares versions
# segment-by-segment numerically, so 2.0.10 correctly supersedes 2.0.3 and
# `dnf upgrade` / `rpm -U` perform a clean in-place upgrade.

# build_rpm <outdir>
build_rpm() {
  local outdir="$1"
  require rpmbuild "Install it with: sudo dnf install rpm-build"

  local top="$WORK/rpmbuild"
  rm -rf "$top"
  mkdir -p "$top"/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

  local spec="$top/SPECS/$AG_ID.spec"
  _write_spec > "$spec"

  log "Building RPM ($AG_ID $AG_VERSION)"
  # The staged tree is handed to rpmbuild via --define; the spec's %install
  # simply copies it into the buildroot, so no compilation happens here.
  rpmbuild -bb \
    --define "_topdir $top" \
    --define "_stagedir $STAGE" \
    --define "_rpmdir $top/RPMS" \
    --target "$AG_ARCH_RPM" \
    --quiet \
    "$spec"

  local built
  built=$(find "$top/RPMS" -name '*.rpm' -type f | head -1)
  [[ -n "$built" ]] || die "rpmbuild produced no package"
  mkdir -p "$outdir"
  mv "$built" "$outdir/"
  ok "RPM: $outdir/$(basename "$built")"
}

# _write_spec - emit the generated RPM spec on stdout.
_write_spec() {
  cat <<EOF
# Generated by packaged-gravity — do not edit by hand.
Name:           $AG_ID
Version:        $AG_VERSION
Release:        1%{?dist}
Summary:        $AG_COMMENT
License:        Proprietary
URL:            https://antigravity.google
ExclusiveArch:  $AG_ARCH_RPM

# The payload is a prebuilt Electron app; keep rpm's helpers from rewriting it.
%global __brp_mangle_shebangs %{nil}
%global __brp_check_rpaths     %{nil}
%global debug_package          %{nil}
# Bundled .so files would otherwise be auto-required from the system.
AutoReqProv:    no

# System libraries the bundled Chromium/Electron runtime needs at start-up.
Requires:       gtk3
Requires:       nss
Requires:       alsa-lib
Requires:       libsecret
Requires:       libnotify

%description
$AG_NAME packaged from the official Google Antigravity Linux release.

$AG_COMMENT.

This RPM bundles its own Electron/Chromium runtime under /opt/$AG_ID and
installs a launcher, desktop entry and icons so it behaves like any other
desktop application and upgrades cleanly through dnf.

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}
cp -a %{_stagedir}/. %{buildroot}/

%files
# Files default to root:root ownership and keep the modes from the staged tree,
# so chrome-sandbox (staged as 4755) is packaged as a setuid-root helper.
/opt/$AG_ID
/usr/bin/$AG_ID
/usr/share/applications/$AG_ID.desktop
/usr/share/icons/hicolor/*/apps/$AG_ID.png
/usr/share/pixmaps/$AG_ID.png
/usr/share/doc/$AG_ID

# Refresh the desktop/icon caches so the launcher shows up immediately.
%post
if [ -x /usr/bin/update-desktop-database ]; then
  update-desktop-database -q /usr/share/applications || :
fi
if [ -x /usr/bin/gtk-update-icon-cache ]; then
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || :
fi

%postun
if [ \$1 -eq 0 ]; then
  if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q /usr/share/applications || :
  fi
  if [ -x /usr/bin/gtk-update-icon-cache ]; then
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || :
  fi
fi

%changelog
* $(LC_ALL=C date '+%a %b %d %Y') packaged-gravity - $AG_VERSION-1
- Packaged from the official Antigravity Linux release.
EOF
}
